### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Apetrou** [Apetrou/AutoManager#1]
- [ ] Routing to all instance

- [ ] Uploader bundle to all instances

- [ ] Redo template for notifications for all instances

- [ ] Do user registrations for all instances
